import "@fontsource/karla";
import "./globals.css";

export const metadata = {
  title: "Afri Food | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-7x mx-aut">{children}</body>
    </html>
  );
}
